services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    command: sh -c "npm install && npm run build"
    volumes:
      - ./frontend:/app
    networks:
      - ng
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env.prod
    expose:
      - "8000"
    networks:
      - ng

  redis:
    volumes:
      - redis-data:/data
  
  nginx:
    image: nginx:latest
    ports: 
      - "80:80"
    volumes:
      - ./nginxprod.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html:ro
    networks:
      - ng
    depends_on:
      - frontend

  db:
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  redis-data:
  postgres_data:

networks:
  ng:
    driver: bridge
