services:
  frontend:
    build:
      context: ./frontend
    command: sh -c "npm install && npm run build"
    volumes:
      - ./frontend:/app
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env.prod

  redis:
    volumes:
      - redis-data:/data
  
  nginx:
    image: nginx:latest
    ports: 
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
    networks:
      - ng

  db:
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  redis-data:
  postgres_data:

networks:
  ng:
    driver: bridge
