services:
  frontend:
    build:
      context: ./frontend
    command: sh -c "npm install && npm run build"
    volumes:
      - ./frontend:/app

  redis:
    volumes:
      - redis-data:/data

volumes:
  redis-data:
