services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"

  backend:
    build:
      context: ./backend
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    command: sh -c "redis-server"
    ports:
      - "6379:6379"
  
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=netdis